<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "",
    "slogan": "",
    "description": "",
    "footer": "Copyright \u00a9 2018 mrdarko.lt",
    "itemsPerPage": "6",
    "language": "lt_LT",
    "locale": "en, en_US, en_AU, en_CA, en_GB, en_IE, en_NZ",
    "timezone": "Europe\/Vilnius",
    "theme": "clean-blog-master",
    "adminTheme": "default",
    "homepage": " ",
    "pageNotFound": "klaida",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "\/blog\/",
    "url": "http:\/\/127.0.0.1",
    "emailFrom": "no-reply@127.0.0.1",
    "orderBy": "position",
    "currentBuild": "20180123",
    "twitter": "",
    "facebook": "https:\/\/www.facebook.com\/WhoIsMrDarko\/",
    "codepen": "",
    "googlePlus": "",
    "instagram": "",
    "github": "",
    "dateFormat": "F j, Y"
}