tinymce.addI18n('ro',{
"Redo": "Repetare",
"Undo": "Anulare",
"Cut": "Decupare",
"Copy": "Copiere",
"Paste": "Lipire",
"Select all": "Selecteaz\u0103 tot",
"New document": "Document nou",
"Ok": "Ok",
"Cancel": "Revocare",
"Visual aids": "Ajutoare vizuale",
"Bold": "Aldin",
"Italic": "Cursiv",
"Underline": "Subliniat",
"Strikethrough": "T\u0103iat",
"Superscript": "Exponent",
"Subscript": "Indice",
"Clear formatting": "\u00cendep\u0103rtare formatare",
"Align left": "Aliniere la st\u00e2nga",
"Align center": "Aliniere la centru",
"Align right": "Aliniere la dreapta",
"Justify": "Aliniere st\u00e2nga-dreapta",
"Bullet list": "List\u0103 marcatori",
"Numbered list": "List\u0103 numerotat\u0103",
"Decrease indent": "Mic\u0219orare indent",
"Increase indent": "M\u0103rire indent",
"Close": "\u00cenchide",
"Formats": "Formate",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Browser-ul dumneavoastr\u0103 nu are acces direct la clipboard. V\u0103 rug\u0103m s\u0103 folosi\u021bi \u00een schimb scurt\u0103turile de tastatur\u0103 Ctrl+X\/C\/V.",
"Headers": "Antete",
"Header 1": "Antet 1",
"Header 2": "Antet 2",
"Header 3": "Antet 3",
"Header 4": "Antet 4",
"Header 5": "Antet 5",
"Header 6": "Antet 6",
"Headings": "Rubrici",
"Heading 1": "Rubrica 1",
"Heading 2": "Rubrica 2",
"Heading 3": "Rubrica 3",
"Heading 4": "Rubrica 4",
"Heading 5": "Rubrica 5",
"Heading 6": "Rubrica 6",
"Preformatted": "Preformatat",
"Div": "Div",
"Pre": "Pre",
"Code": "Code",
"Paragraph": "Paragraf",
"Blockquote": "Citat",
"Inline": "\u00cen linie",
"Blocks": "Sec\u021biuni",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Lipirea este \u00een mod text simplu. Con\u021binutul va fi lipit ca \u0219i text simplu p\u00e2n\u0103 dezactiva\u021bi aceast\u0103 op\u021biune.",
"Fonts": "Fonturi",
"Font Sizes": "Dimensiuni font",
"Class": "Clas\u0103",
"Browse for an image": "C\u0103uta\u021bi o imagine",
"OR": "SAU",
"Drop an image here": "Arunca\u021bi o imagine aici",
"Upload": "\u00cenc\u0103rcare",
"Block": "Sec\u021biune",
"Align": "Aliniere",
"Default": "Implicit",
"Circle": "Cerc",
"Disc": "Disc",
"Square": "P\u0103trat",
"Lower Alpha": "Alfanumeric mic",
"Lower Greek": "Grecesc mic",
"Lower Roman": "Roman mic",
"Upper Alpha": "Alfanumeric mare",
"Upper Roman": "Roman mare",
"Anchor...": "Ancor\u0103\u2026",
"Name": "Nume",
"Id": "Id",
"Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "Id-ul ar trebui s\u0103 \u00eenceap\u0103 cu o liter\u0103, urmat\u0103 doar de litere, numere, cratime, puncte, virgule sau sublinieri.",
"You have unsaved changes are you sure you want to navigate away?": "Ave\u021bi modific\u0103ri nesalvate. Dori\u021bi s\u0103 naviga\u021bi \u00een alt\u0103 parte?",
"Restore last draft": "Restabili\u021bi ultima ciorn\u0103",
"Special characters...": "Caractere speciale\u2026",
"Source code": "Cod surs\u0103",
"Insert\/Edit code sample": "Inserare\/Editare mostr\u0103 cod",
"Language": "Limb\u0103",
"Code sample...": "Mostr\u0103 cod\u2026",
"Color Picker": "Selector culoare",
"R": "R",
"G": "G",
"B": "B",
"Left to right": "De la st\u00e2nga la dreapta",
"Right to left": "De la dreapta la st\u00e2nga",
"Emoticons...": "Emoticoane\u2026",
"Metadata and Document Properties": "Meta date \u0219i Propriet\u0103\u021bi Document",
"Title": "Titlu",
"Keywords": "Cuvinte cheie",
"Description": "Descriere",
"Robots": "Robo\u021bi",
"Author": "Autor",
"Encoding": "Codare",
"Fullscreen": "Ecran \u00eentreg",
"Action": "Ac\u021biune",
"Shortcut": "Scurt\u0103tur\u0103",
"Help": "Ajutor",
"Address": "Adres\u0103",
"Focus to menubar": "Centrare pe bara de meniuri",
"Focus to toolbar": "Centrare pe bara de unelte",
"Focus to element path": "Centrare pe calea elementului",
"Focus to contextual toolbar": "Centrare pe bara de unelte contextual\u0103",
"Insert link (if link plugin activated)": "Inserare link (dac\u0103 modulul de link-uri este activat)",
"Save (if save plugin activated)": "Salvare (dac\u0103 modulul de salvare e activat) ",
"Find (if searchreplace plugin activated)": "C\u0103utare (dac\u0103 modulul de c\u0103utare este activat)",
"Plugins installed ({0}):": "Module instalate: ({0}):",
"Premium plugins:": "Module premium:",
"Learn more...": "Afla\u021bi mai multe\u2026",
"You are using {0}": "Folosi\u021bi {0}",
"Plugins": "Module",
"Handy Shortcuts": "Scurt\u0103turi folositoare",
"Horizontal line": "Linie orizontal\u0103",
"Insert\/edit image": "Inserare\/editare imagine",
"Image description": "Descriere imagine",
"Source": "Surs\u0103",
"Dimensions": "Dimensiuni",
"Constrain proportions": "Constr\u00e2nge propor\u021biile",
"General": "General",
"Advanced": "Avansat",
"Style": "Stil",
"Vertical space": "Spa\u021biu vertical",
"Horizontal space": "Spa\u021biu orizontal",
"Border": "Chenar",
"Insert image": "Inserare imagine",
"Image...": "Imagine\u2026",
"Image list": "List\u0103 imagini",
"Rotate counterclockwise": "Rotire invers sensului acelor de ceasornic",
"Rotate clockwise": "Rotire \u00een sensul acelor de ceasornic",
"Flip vertically": "Inversare vertical\u0103",
"Flip horizontally": "Inversare orizontal\u0103",
"Edit image": "Editare imagine",
"Image options": "Op\u021biuni imagine",
"Zoom in": "Apropiere",
"Zoom out": "Dep\u0103rtare",
"Crop": "T\u0103iere",
"Resize": "Redimensionare",
"Orientation": "Orientare",
"Brightness": "Luminozitate",
"Sharpen": "Accentuare",
"Contrast": "Contrast",
"Color levels": "Niveluri culori",
"Gamma": "Gamma",
"Invert": "Inversare",
"Apply": "Aplic\u0103",
"Back": "\u00cenapoi",
"Insert date\/time": "Inserare dat\u0103\/or\u0103",
"Date\/time": "Dat\u0103\/or\u0103",
"Insert\/Edit Link": "Inserare\/Editare link",
"Insert\/edit link": "Inserare\/editare link",
"Text to display": "Text de afi\u0219at",
"Url": "Url",
"Open link in...": "Deschide link \u00een\u2026",
"Current window": "Fereastra curent\u0103",
"None": "Nedefinit",
"New window": "Fereastr\u0103 nou\u0103",
"Remove link": "Eliminare link",
"Anchors": "Ancore",
"Link...": "Link\u2026",
"Paste or type a link": "Lipi\u021bi sau scrie\u021bi un link",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "URL-ul introdus pare a fi o adres\u0103 de email. Vre\u021bi s\u0103 adaug prefixul mailto: necesar?",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "URL-ul introdus pare a fi un link extern. Vre\u021bi s\u0103 adaug prefixul http:\/\/ necesar?",
"Link list": "List\u0103 link-uri",
"Insert video": "Inserare video",
"Insert\/edit video": "Inserare\/editare video",
"Insert\/edit media": "Inserare\/editare media",
"Alternative source": "Surs\u0103 alternativ\u0103",
"Alternative source URL": "URL surs\u0103 alternativ\u0103",
"Media poster (Image URL)": "Poster media (URL imagine)",
"Paste your embed code below:": "Lipi\u021bi codul de \u00eencorporare mai jos:",
"Embed": "\u00cencorporare",
"Media...": "Media\u2026",
"Nonbreaking space": "Spa\u021biu f\u0103r\u0103 \u00eentreruperi",
"Page break": "\u00centrerupere de pagin\u0103",
"Paste as text": "Lipire ca text",
"Preview": "Previzualizare",
"Print...": "Tip\u0103rire\u2026",
"Save": "Salvare",
"Find": "C\u0103utare",
"Replace with": "\u00cenlocuire cu",
"Replace": "\u00cenlocuire",
"Replace all": "\u00cenlocuire peste tot",
"Previous": "Anterior",
"Next": "Urm\u0103tor",
"Find and replace...": "C\u0103utare \u0219i \u00eenlocuire\u2026",
"Could not find the specified string.": "Nu s-a g\u0103sit niciun rezultat.",
"Match case": "Potrivire caractere",
"Find whole words only": "G\u0103se\u0219te doar cuvintele \u00eentregi",
"Spell check": "Verificare ortografic\u0103",
"Ignore": "Ignor\u0103",
"Ignore all": "Ignor\u0103 tot",
"Finish": "Finalizare",
"Add to Dictionary": "Ad\u0103ugare \u00een Dic\u021bionar",
"Insert table": "Inserare tabel",
"Table properties": "Propriet\u0103\u021bi tabel",
"Delete table": "Eliminare tabel",
"Cell": "Celul\u0103",
"Row": "R\u00e2nd",
"Column": "Coloan\u0103",
"Cell properties": "Propriet\u0103\u021bi celul\u0103",
"Merge cells": "\u00cempreunare celule",
"Split cell": "Desp\u0103r\u021bire celul\u0103",
"Insert row before": "Inserare r\u00e2nd \u00eenainte",
"Insert row after": "Inserare r\u00e2nd dup\u0103",
"Delete row": "Eliminare r\u00e2nd",
"Row properties": "Propriet\u0103\u021bi r\u00e2nd",
"Cut row": "Decupare r\u00e2nd",
"Copy row": "Copiere r\u00e2nd",
"Paste row before": "Lipire r\u00e2nd \u00eenainte",
"Paste row after": "Lipire r\u00e2nd dup\u0103",
"Insert column before": "Inserare coloan\u0103 \u00eenainte",
"Insert column after": "Inserare coloan\u0103 dup\u0103",
"Delete column": "Eliminare coloan\u0103",
"Cols": "Coloane",
"Rows": "R\u00e2nduri",
"Width": "L\u0103\u021bime",
"Height": "\u00cen\u0103l\u021bime",
"Cell spacing": "Spa\u021biere celul\u0103",
"Cell padding": "C\u0103ptu\u0219eal\u0103 celul\u0103",
"Show caption": "Arat\u0103 legenda",
"Left": "St\u00e2nga",
"Center": "Centru",
"Right": "Dreapta",
"Cell type": "Tip celul\u0103",
"Scope": "Arie",
"Alignment": "Aliniament",
"H Align": "Aliniere O",
"V Align": "Aliniere V",
"Top": "Sus",
"Middle": "Mijloc",
"Bottom": "Jos",
"Header cell": "Celul\u0103 antet",
"Row group": "Grupare r\u00e2nduri",
"Column group": "Grupare coloane",
"Row type": "Tip r\u00e2nd",
"Header": "Antet",
"Body": "Corp",
"Footer": "Subsol",
"Border color": "Culoare chenar",
"Insert template...": "Inserare \u0219ablon\u2026",
"Templates": "\u0218abloane",
"Template": "\u0218ablon",
"Text color": "Culoare text",
"Background color": "Culoare fundal",
"Custom...": "Personalizat\u2026",
"Custom color": "Culoare personalizat\u0103",
"No color": "F\u0103r\u0103 culoare",
"Remove color": "Eliminare culoare",
"Table of Contents": "Cuprins",
"Show blocks": "Arat\u0103 rubricile",
"Show invisible characters": "Arat\u0103 caracterele invizibile",
"Word count": "Num\u0103r\u0103toare cuvinte",
"Words: {0}": "Cuvinte: {0}",
"{0} words": "{0} cuvinte",
"File": "Fi\u0219ier",
"Edit": "Editare",
"Insert": "Inserare",
"View": "Vizualizare",
"Format": "Formatare",
"Table": "Tabel",
"Tools": "Unelte",
"Powered by {0}": "Cu sprijinul {0}",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Zon\u0103 Text Formatat. Ap\u0103sa\u021bi ALT-F9 pentru meniu. Ap\u0103sa\u021bi ALT-F10 pentru bara de unelte. Ap\u0103sa\u021bi ALT-0 pentru ajutor.",
"Image title": "Titlu imagine",
"Border width": "Grosime chenar",
"Border style": "Stil chenar",
"Error": "Eroare",
"Warn": "Aten\u021bionare",
"Valid": "Valid",
"To open the popup, press Shift+Enter": "Pentru a deschide popup-ul ap\u0103sa\u021bi Shift+Enter",
"Rich Text Area. Press ALT-0 for help.": "Zon\u0103 Text Formatat. Ap\u0103sa\u021bi ALT-0 pentru ajutor.",
"System Font": "Font Sistem",
"Failed to upload image: {0}": "Nu s-a putut \u00eenc\u0103rca imaginea: {0}",
"Failed to load plugin: {0} from url {1}": "Nu s-a putut \u00eenc\u0103rca modulul: {0} de la URL-ul {1}",
"Failed to load plugin url: {0}": "Nu s-a putut deschide URL-ul modulului: {0}",
"Failed to initialize plugin: {0}": "Nu s-a putut ini\u021bializa modulul: {0}",
"example": "exemplu",
"Search": "C\u0103utare",
"All": "Tot",
"Currency": "Moned\u0103",
"Text": "Text",
"Quotations": "Citate",
"Mathematical": "Matematic",
"Extended Latin": "Latin Extins",
"Symbols": "Simboluri",
"Arrows": "S\u0103ge\u021bi",
"User Defined": "Definite de Utilizator",
"dollar sign": "dolar",
"currency sign": "moned\u0103",
"euro-currency sign": "euro",
"colon sign": "dou\u0103 puncte",
"cruzeiro sign": "cruzeiro",
"french franc sign": "franc francez",
"lira sign": "lira",
"mill sign": "mill",
"naira sign": "naira",
"peseta sign": "peseta",
"rupee sign": "rupee",
"won sign": "won",
"new sheqel sign": "noul sheqel",
"dong sign": "dong",
"kip sign": "kip",
"tugrik sign": "tugrik",
"drachma sign": "drachma",
"german penny symbol": "penny german",
"peso sign": "peso",
"guarani sign": "guarani",
"austral sign": "austral",
"hryvnia sign": "hryvnia",
"cedi sign": "cedi",
"livre tournois sign": "livre tournois",
"spesmilo sign": "spesmilo",
"tenge sign": "tenge",
"indian rupee sign": "rupee indian\u0103",
"turkish lira sign": "lir\u0103 turceasc\u0103",
"nordic mark sign": "marc\u0103 nordic\u0103",
"manat sign": "manat",
"ruble sign": "rubl\u0103",
"yen character": "yen",
"yuan character": "yuan",
"yuan character, in hong kong and taiwan": "yuan \u00een Hong Kong \u0219i Taiwan",
"yen\/yuan character variant one": "yen\/yuan prima variant\u0103",
"Loading emoticons...": "Se \u00eencarc\u0103 emoticoanele\u2026",
"Could not load emoticons": "Nu s-au putut \u00eenc\u0103rca emoticoanele",
"People": "Persoane",
"Animals and Nature": "Animale \u0219i Natur\u0103",
"Food and Drink": "M\u00e2ncare \u0219i b\u0103uturi",
"Activity": "Activit\u0103\u021bi",
"Travel and Places": "C\u0103l\u0103torii \u0219i Loca\u021bii",
"Objects": "Obiecte",
"Flags": "Steaguri",
"Characters": "Caractere",
"Characters (no spaces)": "Caractere (f\u0103r\u0103 spa\u021bii)",
"Error: Form submit field collision.": "Eroare: Coliziune c\u00e2mpuri la trimiterea formularului.",
"Error: No form element found.": "Eroare: Niciun element de formular g\u0103sit.",
"Update": "Actualizare",
"Color swatch": "Specimene culori",
"Turquoise": "Turcoaz",
"Green": "Verde",
"Blue": "Albastru",
"Purple": "Mov",
"Navy Blue": "Albastru marin",
"Dark Turquoise": "Turcuaz \u00eenchis",
"Dark Green": "Verde \u00eenchis",
"Medium Blue": "Albastru mediu",
"Medium Purple": "Mov mediu",
"Midnight Blue": "Albastru \u00eenchis",
"Yellow": "Galben",
"Orange": "Portocaliu",
"Red": "Ro\u0219u",
"Light Gray": "Gri deschis",
"Gray": "Gri",
"Dark Yellow": "Galben \u00eenchis",
"Dark Orange": "Portocaliu \u00eenchis",
"Dark Red": "Ro\u0219u \u00eenchis",
"Medium Gray": "Gri mediu",
"Dark Gray": "Gri \u00eenchis",
"Black": "Negru",
"White": "Alb",
"Switch to or from fullscreen mode": "Comutare la sau de la modul ecran complet",
"Open help dialog": "Deschide dialogul de ajutor",
"history": "istoric",
"styles": "stiluri",
"formatting": "formatare",
"alignment": "aliniament",
"indentation": "indentare",
"permanent pen": "stilou permanent",
"comments": "comentarii"
});